<?php
$this->headTitle('Add User');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItem([
    'Home' => $this->url('home'),
    'Manager Users' => $this->url('users'),
    'Add User' => $this->url('users', ['action' => 'add'])
]);

$form->get('email')->setAttribute([
    'class' => 'form-control',
    'placeholder' => 'name@example.com'
]);

$form->get('full_name')->setAttribute([
    'class' => 'form-control',
    'placeholder' => 'John Does'
]);

$form->get('status')->setAttribute([
    'class' => 'form-control'
]);

$form->get('password')->setAttribute([
    'class' => 'form-control'
]);

$form->get('confirm_password')->setAttribute([
    'class' => 'form-control'
]);

$form->get('submit')->setAttribute(['class' => 'btn btn-primary']);

$form->prepare();
?>
<h1>Add User</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')) ?>
            <?= $this->formElement($form->get('email')) ?>
            <?= $this->formElementErrors($form->get('email')) ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')) ?>
            <?= $this->formElement($form->get('full_name')) ?>
            <?= $this->formElementErrors($form->get('full_name')) ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('password')) ?>
            <?= $this->formElement($form->get('password')) ?>
            <?= $this->formElementErrors($form->get('password')) ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_password')) ?>
            <?= $this->formElement($form->get('confirm_password')) ?>
            <?= $this->formElementErrors($form->get('confirm_password')) ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')) ?>
            <?= $this->formElement($form->get('status')) ?>
            <?= $this->formElementErrors($form->get('status')) ?>
        </div>

        <?= $this->formElement($form->get('submit')) ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
