<?php
$this->headTitle('Change Password');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Manage Users' => $this->url('users'),
    'Change Password' => $this->url('users', ['action' => 'change-password', 'id' => $user->getId()])
]);


$form->get('old_password')->setAttribute([
    'class' => 'form-control',
    'placeholder' => 'Enter old password'
]);

$form->get('new_password')->setAttribute([
    'class' => 'form-control',
    'placeholder' => 'Enter new password'
]);

$form->get('confirm_new_password')->setAttribute([
    'class' => 'form-control',
    'placeholder' => 'Confirm new password'
]);

$form->get('submit')->setAttribute(['class' => 'btn btn-primary']);

$form->prepare();
?>

<h1>Change password for <?= $this->escapeHtml($user->getEmail()) ?></h1>

<div class="row>">
    <div class="col-md-6">
        <?= $this->form()->openTag($form) ?>

        <div class="form-control">
            <?= $this->formLabel($form->get('old_password')) ?>
            <?= $this->formElement($form->get('old_password')) ?>
            <?= $this->formElementErrors($form->get('old_password')) ?>
        </div>

        <div class="form-control">
            <?= $this->formLabel($form->get('new_password')) ?>
            <?= $this->formElement($form->get('new_password')) ?>
            <?= $this->formElementErrors($form->get('new_password')) ?>
        </div>

        <div class="form-control">
            <?= $this->formLabel($form->get('confirm_new_password')) ?>
            <?= $this->formElement($form->get('confirm_new_password')) ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')) ?>
        </div>

        <?= $this->formElement($form->get('csfr')) ?>

        <?= $this->formElement($form->get('submit')) ?>

        <?= $this->form()->closeTag() ?>
    </div>
</div>